apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  scope: Namespaced
  names:
    kind: TFJob
    singular: tfjob
    plural: tfjobs
  versions:
  - name: v1
    served: true
    storage: true
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.tfReplicaSpecs.Worker.replicas
      # Should we have a total replicas?
      statusReplicasPath: .status.replicaStatuses.Active
      labelSelectorPath: .status.labelSelector